# docker-compose.yml

version: "3.9"
services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports: 
      - '5432:5432'
    volumes:
      - auth-db:/var/lib/postgresql/data

  auth:
    build:
      context: .
    environment:
      NODE_ENV: production
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      JWT_SECRET: SECRET_KEY
    depends_on:
      - postgres
    ports:
      - '3000:3000'
        
volumes:
  auth-db:
    driver: local